### ISSUE TITLE
Adding Python3 Support

### ISSUE THREAD

**Issue by codingsett** [DogFive/pyCoinPayments#1]
Hello thanks for making this script ,if you have time can you convert the code to be usable in python3 since per my understanding urllib2 was combined to urrlib in python 3 and when i try to run use the code i get errors. Thanks

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
I can definitely do that. Python 3 is the 'official' python now and this client should reflect that. I'll leave this open and append a commit when it's finished.

**Comment by codingsett** [comment]
I had to convert this library to python 3 to use . Also if you have time please add [IPNs](https://www.coinpayments.net/merchant-tools-ipn) since at the moment there is no way to get the transaction info through this library .Thanks for your efforts for  making my life easier.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Send me a pull request with the Python3 updates and I'll add IPNs

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@codingsett updated to python3 in commit e070f77eaf469aa4ed61839acdbde0ad68220dba

Let me know how it works. Sorry for the delay.

> Also if you have time please add IPNs since at the moment there is no way to get the transaction info through this library

IPNs are apart of this library. Did you want to pass in a different IPN to each request?

**Comment by codingsett** [comment]
Thanks for the update sorry i have been very busy..actually i dont need the IPNs anymore....i used getTransactioninfo api call to know whether somebody paid or not anyway i will check the new updated library and give you my feedback
