### ISSUE TITLE
{ValueError}Type names and field names must be valid identifiers: '777'

### ISSUE THREAD

**Issue by zavod** [DogFive/pyCoinPayments#2]
Hello! I got the issue on rates() method: 
`{ValueError}Type names and field names must be valid identifiers: '777'`
Python 3.6

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Can you post the parameters you sent?

It looks like you're sending an unknown fieldname. See this documentation page about the possible field names for the rates() methods.


https://www.coinpayments.net/apidoc-rates

**Comment by zavod** [comment]
I sent it without parameters, like instance.rates()

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Ah, okay I think I already know the problem. Let me test it tonight and get back to you.

**Comment by zavod** [comment]
Thank you, Man! And one more thing: 
validate_mac method has YOUR_API_KEY variable. 
It's better to set it to the initialization of the class or other place

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Sorry about the lateness on this, I had an email stream going back and forth between coinpayments. It's a weird thing happening in the API. I'll fix this soon.

> validate_mac method has YOUR_API_KEY variable. It's better to set it to the initialization of the class or other place

Whoops, I didn't even mean to push this to the repo yet. I'm writing other code that helps with recieving callbacks. This will be fixed in the next rev

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
All cleaned up

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
> 
> 
> Thank you, Man! And one more thing:
> validate_mac method has YOUR_API_KEY variable.
> It's better to set it to the initialization of the class or other place

Oh also changed the example to reflect not having the api keys stored anywhere like that
