### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bitog** [DogFive/pyCoinPayments#4]
Hi there,

I am getting the following error `ImportError: cannot import name 'CryptoPayments'`.

Module has been importet with `from CryptoPayments import CryptoPayments`.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
What does your folder structure look like? Or where does the wrapper reside?

**Comment by bitog** [comment]
I placed the folder right next to my `main.py` file. Structure is as follows:

`pyCoinPayments` (Folder)
`config.py`
`main.py`

Thanks for your help.

**Comment by bitog** [comment]
Made it to work. Had to move the `.py` file right next to my `main.py`

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@dducted 

I thought it had something to do with that. Glad you got it fixed!
